[tool.poetry]
name = "KAMPING"
version = "1.0"
description = "KEGG automated metabolite protein interaction network generator (KAMPING)"
authors = ["Everest Uriel Castaneda <everest_castaneda1@baylor.edu>"]
readme = "README.rst"
license = "LICENSE"
packages = [
    { include = "KAMPING", from = "." }
]

[tool.poetry.scripts]
KAMPING = "KAMPING.main:app"

[tool.poetry.dependencies]
python = "^3.10"
networkx = "^3.1"
click = "^8.1.3"
pandas = "^2.0.2"
typer = "^0.9.0"
requests = "^2.31.0"
pathlib = "^1.0.1"
scikit-mol = "^0.3.1"
rdkit = "^2024.3.5"
numpy = "^1"

[tool.poetry.group.dev.dependencies]
importlib = "^1.0.4"
matplotlib = "^3.9.2"
qtconsole = "^5.6.0"


[tool.poetry.group.tests.dependencies]
pytest = "^8.3.3"
snapshottest = "^0.6.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[project.urls]
"Homepage" = "https://github.com/everest-castaneda/knext"
"Bug Tracker" = "https://github.com/everest-castaneda/knext/issues"
